export * from './research-library.js'
export * from './workbench.js'
export type { ProductPosition, PortfolioEvent, ProductEquitySnapshot } from '@vibe-invest/domain/portfolio'
export type { ProfitProtectionPlanRecord } from '@vibe-invest/domain/profit-protection'
export type { ProfitProtectionStateRecord, ProfitProtectionTriggerRecord } from '@vibe-invest/domain/profit-protection'
export { schemaVersion, createPool, migrate, checkSchema, type ProductPool } from './schema.js'
export { createRuntimeSettingsRepository, type RuntimeSettingsRepository } from './settings.js'
export { type MigrationVerificationState, type LegacyPortfolioMigration, executeLegacyPortfolioMigration, verifyLegacyPortfolioMigration, createPortfolioRepository, type PortfolioRepository } from './portfolio.js'
export { createProfitProtectionRepository, type ProfitProtectionRepository } from './profit-protection.js'
export { type AnalysisRecord, createAnalysisRepository, type AnalysisRepository, type ConversationThreadInput, type ConversationRunInput, createConversationRepository, type ConversationRepository } from './research.js'
export { type AgentEvent, type AgentSession, createAgentEventRepository, type AgentEventRepository, type ToolProjectionRole, type ToolProjectionStage, createToolProjectionRepository, type ToolProjectionRepository } from './agent-runtime.js'
export { createTrackingRepository, type TrackingRepository } from './tracking.js'
